# Generated by Django 4.2.6 on 2023-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('not', 'Hələ başlanmayıb'), ('progress', 'Davam edir'), ('finish', 'Bitib')], max_length=255, null=True, verbose_name='Taskin statusu'),
        ),
    ]
